### ISSUE TITLE
inference Error

### ISSUE THREAD

**Issue by chunguGuo** [wenxinxu/resnet_in_tensorflow#14]
When I call inference, I got  an error:
Traceback (most recent call last):
  File "/home/forever/PycharmProjects/PIG/resnet.py", line 313, in <module>
    conv9_out = inference(x, FLAGS.num_residual_blocks, reuse=False)
  File "/home/forever/PycharmProjects/PIG/resnet.py", line 194, in inference
    assert conv3.get_shape().as_list()[1:] == [8, 8, 64]
AssertionError

can you tell where should I change my code?

**Comment by HansRen1024** [comment]
did u solve this error? I got this error too.

**Comment by YoungsonZhao** [comment]
Same error, does anyone have a solution?
