### ISSUE TITLE
all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by sky1122** [wenxinxu/resnet_in_tensorflow#35]
working on python3 
and have changed cPickle to pickle && data = dicts['data'] to data = dicts.get('data')

I am encountering a problem about 
**ValueError: all the input arrays must have same number of dimensions**
in cifar10_input.py 

Traceback (most recent call last):
  File "/data/tmp/pycharm_project_979/cifar10_train.py", line 425, in <module>
    train.train()
  File "/data/tmp/pycharm_project_979/cifar10_train.py", line 86, in train
    all_data, all_labels = prepare_train_data(padding_size=FLAGS.padding_size)
  File "/data/tmp/pycharm_project_979/cifar10_input.py", line 176, in prepare_train_data
    data, label = read_in_all_images(path_list, is_random_label=TRAIN_RANDOM_LABEL)
  File "/data/tmp/pycharm_project_979/cifar10_input.py", line 96, in read_in_all_images
    data = np.concatenate((data, batch_data))

and when I print (data.shape) it shows (0, 3072), print(batch_data) it shows None  

How can I fix the problem?

**Comment by gaowq2017** [comment]
data = np.array([]).reshape([0,IMG_WIDTH])
