### ISSUE TITLE
there are no way to test only?

### ISSUE THREAD

**Issue by wonny2001** [wenxinxu/resnet_in_tensorflow#7]
i successed to train the model in my pc.
but i can't get accuracy of test.

there are no way to test only?
when i checked test(self, test_image_array) method
there are no call.

**Comment by wonny2001** [comment]
I made codes like below but it made a error
<codes>
train = Train()
# Start the training session
# train.train()
test_image_array = [128, 32, 32, 3]
top1_error, loss = train.test(test_image_array)


<error>
Traceback (most recent call last):
  File "/home/rainman/src/resnet-in-tensorflow/cifar10_train.py", line 426, in <module>
    top1_error, loss = train.test(test_image_array)
  File "/home/rainman/src/resnet-in-tensorflow/cifar10_train.py", line 232, in test
    saver.restore(sess, FLAGS.test_ckpt_path)
  File "/home/rainman/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1428, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/rainman/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/rainman/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/rainman/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/rainman/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_110.ckpt-79999
	 [[Node: save/RestoreV2_31 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_31/tensor_names, save/RestoreV2_31/shape_and_slices)]]
	 [[Node: save/RestoreV2_18/_155 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_442_save/RestoreV2_18", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by sakshi404** [comment]
Were you able to find the accuracy of the model?
